Repository ProjetVoyage/Tripy, pull requests merged in 2019-03, with the labels that each got.

#17 Document
  config/services.yaml
  src/Controller/Backend/DocumentController.php
  src/Controller/Backend/FolderController.php
  src/Controller/Backend/TravelController.php
  src/Controller/Backend/TravelerController.php
  src/Entity/Document.php
  src/Entity/Folder.php
  src/Entity/Travel.php
  src/Entity/Traveler.php
  src/Form/DocumentType.php
  src/Form/FolderType.php
  src/Form/TravelerType.php
  templates/backend/document/_delete_form.html.twig
  templates/backend/document/_form.html.twig
  templates/backend/document/edit.html.twig
  templates/backend/document/index.html.twig
  templates/backend/document/new.html.twig
  templates/backend/document/show.html.twig
  templates/backend/folder/_delete_form.html.twig
  templates/backend/folder/_form.html.twig
  templates/backend/folder/edit.html.twig
  templates/backend/folder/index.html.twig
  templates/backend/folder/new.html.twig
  templates/backend/folder/show.html.twig
  templates/backend/travel/show.html.twig
  templates/backend/traveler/image.png
  templates/backend/traveler/show.html.twig
Labels: Review

#19 Display document
  .gitignore
  src/Controller/Backend/DocumentController.php
  templates/backend/document/show.html.twig
Labels: enhancement

#21 Add user fixture
  composer.json
  composer.lock
  config/bundles.php
  src/DataFixtures/AppFixtures.php
  symfony.lock
Labels: enhancement

#23 Upgrade bootstrap and fix vulnerability
  package-lock.json
  package.json
Labels: bug
